{% set name = "chembl_webresource_client" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/74/c4/6526156c7e2f164a0fc061aae20d383f0b6b1e79957510a64382e676e2dc/chembl-webresource-client-0.10.1.tar.gz
  sha256: e4bd01ebc0e7efb028b54ea2f5a6fa70a1e8cf930da12c93811908c11fcb11eb

build:
  noarch: python
  number: 0
  entry_points:    
    - chembl_ids=chembl_webresource_client.scripts.chembl_ids:main
    - chembl_sim=chembl_webresource_client.scripts.chembl_sim:main
    - chembl_sub=chembl_webresource_client.scripts.chembl_sub:main
    - chembl_m2t=chembl_webresource_client.scripts.chembl_m2t:main
    - chembl_t2m=chembl_webresource_client.scripts.chembl_t2m:main
    - chembl_act=chembl_webresource_client.scripts.chembl_act:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - easydict
    - grequests
    - pip
    - python
    - requests_cache
  run:
    - easydict
    - grequests
    - python
    - requests_cache
    - six
test:
  imports:
    - chembl_webresource_client
    - chembl_webresource_client.new_client

about:
  home: https://www.ebi.ac.uk/chembldb/index.php/ws
  license: Apache-2.0
  license_family: APACHE
  summary: Python client for accessing ChEMBL webservices.
  license_file: LICENSE
  doc_url: https://chembl.gitbook.io/chembl-interface-documentation/web-services
  dev_url: https://github.com/chembl/chembl_webresource_client

extra:
  recipe-maintainers:
    - simonbray
