{% set name = "chembl_webresource_client" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/chembl-webresource-client/chembl-webresource-client-{{ version }}.tar.gz
  sha256: b175383e8a8809c61e6af500fd6afb9e509bd236fd422cb569a3d549de7258a2

build:
  noarch: python
  number: 0
  entry_points:    
    - chembl_ids=chembl_webresource_client.scripts.chembl_ids:main
    - chembl_sim=chembl_webresource_client.scripts.chembl_sim:main
    - chembl_sub=chembl_webresource_client.scripts.chembl_sub:main
    - chembl_m2t=chembl_webresource_client.scripts.chembl_m2t:main
    - chembl_t2m=chembl_webresource_client.scripts.chembl_t2m:main
    - chembl_act=chembl_webresource_client.scripts.chembl_act:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - easydict
    - grequests
    - pip
    - python >=3.6
    - requests-cache
  run:
    - easydict
    - grequests
    - python >=3.6
    - requests-cache
    - six
test:
  imports:
    - chembl_webresource_client
    - chembl_webresource_client.new_client

about:
  home: https://www.ebi.ac.uk/chembldb/index.php/ws
  license: Apache-2.0
  license_family: APACHE
  summary: Python client for accessing ChEMBL webservices.
  license_file: LICENSE
  doc_url: https://chembl.gitbook.io/chembl-interface-documentation/web-services
  dev_url: https://github.com/chembl/chembl_webresource_client

extra:
  recipe-maintainers:
    - simonbray
