{% set name = "chembl_webresource_client" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/df/0c/7075cb18caa81aaec744ccf26f810535b00388a68b1fa20a9e94209cfb93/chembl-webresource-client-{{ version }}.tar.gz
  sha256: 54e71ccdfc653473055c1b5c5292d5ddb31a7f4c33f54f78996922d50fa8bb03

build:
  number: 0
  skip: true  # [win]
  entry_points:    
    - chembl_ids=chembl_webresource_client.scripts.chembl_ids:main
    - chembl_sim=chembl_webresource_client.scripts.chembl_sim:main
    - chembl_sub=chembl_webresource_client.scripts.chembl_sub:main
    - chembl_m2t=chembl_webresource_client.scripts.chembl_m2t:main
    - chembl_t2m=chembl_webresource_client.scripts.chembl_t2m:main
    - chembl_act=chembl_webresource_client.scripts.chembl_act:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - easydict
    - grequests
    - pip
    - python 3.6.*
    - requests_cache
  run:
    - easydict
    - grequests
    - python 3.6.*
    - requests_cache
    - six
test:
  imports:
    - chembl_webresource_client
    - chembl_webresource_client.new_client

about:
  home: https://www.ebi.ac.uk/chembldb/index.php/ws
  license: Apache-2.0
  license_family: APACHE
  summary: Python client for accessing ChEMBL webservices.
  license_file: LICENSE
  doc_url: https://chembl.gitbook.io/chembl-interface-documentation/web-services
  dev_url: https://github.com/chembl/chembl_webresource_client

extra:
  recipe-maintainers:
    - simonbray
