travis:
  secure:
    BINSTAR_TOKEN: Ajza6WHM+Cpiyy+9Ixl3XT6BB8LrmO22DHSR/kZwi4Xm5Eda2urGW0ThqiRHkX55X776QE+pAwBOWafZxLVj3dkH6rKfcZVfmXyi+UJhQykjhkN/jFEdKEZT+tOIJnD9H1ttccwDefyCQXe1gwTgCXVd63QRbFsHULQa+OXcB5IlqsYAjqt0fX0bzqjP5oic3lo7QX/mPIkt+wKcLoHUniwyzOPEmiJHwGneFdDTCb+2LjKd/aO8mKgnleqRbz9riJq5h5fxaBWKk/SjdDhwptELy6tJZx3CZQcYEFXWpizcSP73Vhg+PR+DESbWno4uTxXaTL1zwecm7KMuIyEir0Cm2te3L3DSMhDSBlOtdaguAfb3X87oZFPMcJULQGJ4cMQPpbHdkhrpIud/GbHooNu9Ofnko3Um4IkpUdEUBNE/21g0aP+dyRu+UlND0Pa3OO9ZUtTar7VLk3cgF3wEHD/8D3U70atVMUX8RYpy1qPKGhmjo7+zm6v9Ydp1K2DvHnl2jIckReP18J0YAThn4t8oH+s4wNY57NnDOTFl1nFDoqrE8lNNju9m1l+Z3DNxw00xTliNLpPdQSIUkeGzSIoEYGdcgeQPdDM0ffrrM5kXgws0gXcrNKFF7P2Ax70ET3LllgBwF/ZTII8gfDAp/ECNMsVltYxiRjxKj09pd6c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
